# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


def set_attrs_to_false(apps, schema_editor):
    ProductAttribute = apps.get_model('product', 'productattribute')
    for attr in ProductAttribute.objects.all():
        attr.hidden = False


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_attrs_to_false)
    ]
