# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 23:36
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_auto_20180208_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='categories'),
        ),
    ]
