# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_merge_20180211_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
