# Generated by Django 2.0.3 on 2018-03-28 07:51

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_auto_20180326_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ignore_stock',
            field=models.BooleanField(default=False),
        ),
    ]
