# Generated by Django 2.0.3 on 2018-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0011_auto_20180108_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
