files:
  - source: /locale/*/LC_MESSAGES/*.po
    translation: /locale/%two_letters_code%/LC_MESSAGES/%file_name%.po
    languages_mapping:
      two_letters_code:
        fr: fr
        de: de
        tr: tr
