# Generated by Django 2.0.3 on 2018-03-28 11:35

from django.db import migrations
import django_positions_2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageitem',
            options={
                'ordering': ('position',),
                'permissions': (
                    ('view_blocks_config', 'Can view home page configuration'),
                    ('edit_blocks_config', 'Can edit home page configuration'))
            },
        ),
        migrations.AlterField(
            model_name='homepageitem',
            name='position',
            field=django_positions_2.fields.PositionField(blank=True, default=-1),
        ),
    ]
