# Generated by Django 2.0.2 on 2018-03-19 03:06

from django.conf import settings
from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0007_auto_20180108_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        )
    ]
