# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20180123_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
