# Generated by Django 2.0.2 on 2018-03-25 07:03

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20180216_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(default=False),
        )
    ]
